- name: Update all packages
  yum:
    name: "*"
    state: latest

- name: Install Nginx
  yum:
    name: nginx
    state: present

- name: Start and enable nginx service
  service:
    name: nginx
    state: started
    enabled: yes

- name: Deploy custom index.html
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
    owner: nginx
    group: nginx
    mode: 0644
